- name: demo on task level variables
  hosts: localhost
  connection: local # it will not ask for username ans password
  vars:
    COURSE: "Ansible"
    Trainer: "Siva"
    Duration: "150 hrs"
  tasks:
  - name: print information
    vars:
      COURSE: "DevSecops with AIOps"  # task level child will override the child in var
    debug: #inorder to print something debug is used
      msg: " I'am learning {{COURSE}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
     