# command line arguments
# if u r not defining variable anywhere in file then u can pass variables as command line arguments
- name: demo vars from cmd 
  hosts: local
  connection: local
  tasks:
   - name: print local
     debug:
       msg: "Hello {{name}}"
