- name: variable preferences
  hosts: local
  connection: local
  vars: # vars play level
    full_name: "siva from play"
  vars_files: # vars file
  - course.yaml   
  vars_prompt: # vars prompt
  - name: full_name
    prompt: "please enter your full_name"
    private: false
  tasks: # vars task
  - name: print vars preference
    vars: 
      full_name: "siva from TASK Level"
    debug: # vars inventory
      msg: "hi, {{full_name}}"  
