- name: course information
  hosts: local
  connection: local
  vars:
    course: "DevSecops with AIops" # string
    duration_in_hrs: 150 # int/number
    is_live_sessions: true # boolean
    topics: # list
    - linux
    - shell
    - ansible
    more_details:  # map - contains multiple key value pairs
      months: "5"  # u can give like string within "" or as interger without quotes 
      trainer: "sivakumar reddy"
  tasks:
  - name: print information
    debug:
      msg: | # if we want to give multiple lines in a msg then use the pipe symbol as used here
        name: {{ course }}
        duration: {{ duration_in_hrs }}
        is_it_live: {{ is_live_sessions }}
        topics: {{ topics }}
        more_details: {{ more_details }}


