- name: conditions using ansible facts
  hosts: frontend
  tasks:
  - name: print if redhat
    debug:
      msg: "OS family is Redhat, package manager is dnf"
    when: ansible_facts.os_family == "redhat"  

  - name: print if Debian
    debug:
      msg: "OS family is Debian, package manager is apt-get"
    when: ansible_facts.os_family == "Debian"  