- name: Demo on Filters
  hosts: local
  connection: local
  vars:
   topics: Linux, Shell, Ansible, Terraform
  tasks:
  - name: convert string to list
    debug:
     msg: "Topics are: {{ topics | split(',') }}" # split is the one which is used as to print the variable as list

  - name: set default value
    debug:
      msg: "Hi, {{ Greetings | default('Good Mrng') }}" # we can use default() as default variable for any variables that we give
