- name: Demo on Filters
  hosts: local
  connection: local
  vars:
   topics: Linux, Shell, Ansible, Terraform
   tagMap: # ansible map to list
     name: Ansible
     project: Roboshop
     environment: dev
   full_name: Lokam Sai Nithisha 
   tagslist:  [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "environment",
            "value": "dev"
        }
    ]
  tasks:
  - name: convert string to list
    debug:
     msg: "Topics are: {{ topics | split(',') }}" # split is the one which is used as to print the variable as list

  - name: set default value
    debug:
      msg: "Hi, {{ Greetings | default('Good Mrng') }}" # we can use default() as default variable for any variables that we give, when we haven't given value anywhere
  
  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}" # this dict2items is used for converting map to list

  - name: convert list to map 
    debug:
      msg: "{{ tagslist | items2dict }}" # this items2dict is used for converting list to map

  - name: convert to Uppercase
    debug:
      msg: "{{ full_name | upper }}" # to convert lowercase to uppercase

  - name: convert to Uppercase
    debug:
      msg: "{{ full_name | lower }}" # to convert uppercase to lowercase   