- name: Demo on shell Vs command
  hosts: local
  connection: local
  tasks:
  - name: command test
    #command: cat /etc/passwd | grep root # pipes should need shell permissions the command will fail in ansible
    shell: cat /etc/passwd | grep root
    register: users_output # register key word is used to take the output into a variable

  - name: print output
    debug:
     msg: "{{ users_output }}"

  - name: list files
    #command: ls -ltr > /tmp/files.txt # redirection fails      
    shell:  ls -ltr > /tmp/files.txt # shell it will get succeded