- name: Demo on shell Vs command
  hosts: local
  connection: local
  tasks:
  - name: command test
    #command: cat /etc/passwd | grep root # pipes should need shell permissions the command will fail in ansible
    shell: cat /etc/passwd | grep root
    