- name: demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exit or not
    command: id roboshop
    register: user_output
    ignore_errors: true  # it is known error so we r ignoring the error by using the ignore_error

  - name: print user_output
    debug:
      msg: "{{ user_output }}"
    #command: useradd roboshop